### ISSUE TITLE
Quoted tokens are badly recognized

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#3] opened 2019-04-05 10:32 UTC
I noticed that recognition of quoted tokens is not working correctly in version 0.1.0 and 0.2.0.

When I ask some query and on the end of query has quoted word "balloon"
then it is recognized as two separated tokens:

![separated](https://user-images.githubusercontent.com/13571369/55621718-95221980-579e-11e9-9e43-b65d90310848.PNG)

In efect it isn't possible to recognize quoted tokens correctly and nlp:quoted is useless in this case.

**Comment by skhdl** [comment] 2019-04-05 10:36
Thank you for your feedback, we'll try to resolve it as soon as possible
(in next release - version 0.3.0)

**Comment by aradzinski** [comment] 2019-04-05 17:50
This looks like a clear regression. Will be addressed shortly in 0.3.0

**Comment by vic64** [comment] 2019-04-10 19:19
Fixed in 0.3.0 release.

**Closed by vic64** 2019-04-10 19:19 UTC
Labels: bug
