### ISSUE TITLE
unexpected behavior with limit function and date

### ISSUE THREAD

**Issue by ermadan** [vic64/nlpcraft#40] opened 2019-05-03 18:52 UTC
intent:
````
        solver.addIntent(NCIntentSolver.CONV_INTENT(
                "salesClient",
                NCIntentSolver.TERM(NCIntentSolver.AND("id == nlp:function", "~FUNCTION_TYPE == LIMIT"), 0, 1),
                NCIntentSolver.TERM("id == aspen:salesclient", 0, 1),
                NCIntentSolver.TERM("id == aspen:period", 0, 1),  //optional period token
                NCIntentSolver.TERM("id == nlp:geo", 0, 1),
                NCIntentSolver.TERM("id == nlp:date", 0, 1)          // Term #2 (index 1): optional date.
````
sequence of requests:
1. top 5 sales in europe in february
2. in last year
second request gets processes as:
````
May-03 14:37:36 [INFO ] Found matching intents (sorted from best to worst match):
+============================================================================================================+
| Variant |   Intent    |                                       Tokens                                       |
+============================================================================================================+
| #2      | salesClient | INTENT: 'salesClient'                                                              |
|         |             |   Group #0                                                                         |
|         |             |     #0: Token [id=nlp:function, text=last, group=nlp:function, value=null]         |
|         |             |   Group #1                                                                         |
|         |             |     #0: (conv) Token [id=aspen:salesclient, text=sales, group=null, value=null]    |
|         |             |   Group #2                                                                         |
|         |             |     <empty>                                                                        |
|         |             |   Group #3                                                                         |
|         |             |     #0: (conv) Token [id=nlp:geo, text=europe, group=nlp:geo, value=null]          |
|         |             |   Group #4                                                                         |
|         |             |     #0: (conv) Token [id=nlp:date, text=in february, group=nlp:date, value=null]   |
+---------+-------------+------------------------------------------------------------------------------------+
| #1      | salesClient | INTENT: 'salesClient'                                                              |
|         |             |   Group #0                                                                         |
|         |             |     #0: (conv) Token [id=nlp:function, text=top 5, group=nlp:function, value=null] |
|         |             |   Group #1                                                                         |
|         |             |     #0: (conv) Token [id=aspen:salesclient, text=sales, group=null, value=null]    |
|         |             |   Group #2                                                                         |
|         |             |     <empty>                                                                        |
|         |             |   Group #3                                                                         |
|         |             |     #0: (conv) Token [id=nlp:geo, text=europe, group=nlp:geo, value=null]          |
|         |             |   Group #4                                                                         |
|         |             |     #0: Token [id=nlp:date, text=last year, group=nlp:date, value=null]            |
+------------------------------------------------------------------------------------------------------------+
````
expected order is vice versa

**Comment by aradzinski** [comment] 2019-05-08 16:25
Moving to the next release - can't reproduce in 0.5.0

**Comment by aradzinski** [comment] 2019-05-29 23:36
Closing for now. Reopen if reproduced.

**Closed by aradzinski** 2019-05-29 23:36 UTC
Labels: bug, working
